# Generated by Django 4.0.4 on 2022-05-19 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('todo', '0001_create_model_todo'), ('todo', '0002_expiration_time_for_todo'), ('todo', '0003_rename_expirated_at_todo_expired_at'), ('todo', '0004_label_model'), ('todo', '0005_alter_todolabel_label'), ('todo', '0006_label_and_priority_field_for_todo'), ('todo', '0007_status_field_for_todo')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='todo.todolabel')),
                ('priority', models.CharField(choices=[('1', 'LOW'), ('2', 'MIDDLE'), ('3', 'HIGH'), ('4', 'EXTRA HIGH')], default='2', max_length=2)),
                ('status', models.CharField(choices=[('1', 'TODO'), ('2', 'IN PROGRESS'), ('3', 'ON HOLD'), ('4', 'COMPLETE')], default='1', max_length=2)),
            ],
        ),
    ]
