# Generated by Django 4.0.4 on 2022-07-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_alter_phrase_source_lang_alter_phrase_target_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='label',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='languages.languageslabel'),
        ),
    ]
